# Generated by Django 3.2.6 on 2021-08-19 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Author email')),
                ('content_text', models.TextField(max_length=100, validators=[django.core.validators.MaxLengthValidator(100, 'Max length is 100!'), django.core.validators.MinLengthValidator(1, 'Message cannot be empty!')], verbose_name='Message text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of update')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
